#app
server:
    port: 8080
    context-path: /aod-feed

#spring
spring:
  devtools:
    restart:
      enabled: false
  http:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 50MB
      max-request-size: 100MB
      resolve-lazily: false

  # mysql DATABASE CONFIG
  datasource:
    #指定自定义连接池
    type: com.zaxxer.hikari.HikariDataSource
    #指定数据库连接信息
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.1.201:3306/AODFeedDev?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    username: root
#    password: admin01
    url: jdbc:mysql://172.42.3.233:3306/crm2017?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql01


    #初始化数据库脚本
    initialize: true
    platform: mysql
    #schema: classpath:/db/schema-h2.sql
    #data: classpath:/db/data-h2.sql
    continue-on-error: true
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
      auto-commit: true
      connection-test-query: select 1

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sinosoft.aod.model
  #typeEnumsPackage: com.sinosoft.cmp.demo.user.model.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.sinosoft.cmp.demo
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.sinosoft.cmp.demo.xxx
    #自定义SQL注入器
    #sql-injector: com.sinosoft.cmp.demo.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  level: debug



#服务信息
serviceInfo:
    url: http://172.42.3.34:9001/aodfeed
#    url: http://192.168.1.126:9001/aodfeed
    tenantId: BaiQian



